# Use the official image as a parent image
FROM centos:7 AS rcms-nginx-build

MAINTAINER eduardobc.88@gmail.com

# Set the working directory
WORKDIR /reactive-cms/

# Run the command inside your image filesystem
RUN yum install epel-release -y && yum update -y
RUN yum install nginx -y

# Volumes to share with host
VOLUME /reactive-cms/

# Command to exec when the container start up
ENTRYPOINT cp ./nginx.conf /etc/nginx/nginx.conf && nginx && /bin/bash
